# Generated by Django 2.2.28 on 2023-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230304_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_field_added',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
